default:
  recovery.mode : false # all data for analysis are preprocessed and saved to a disk after first run. After they could be reused in recovery.mod
  install.libraries: false
  is.case.control.analysis: true # to separate preprocessing step betweem HA dataset and multigroup
  project.dir: "/projects/cgstudies/HA_GWAS_2017/Healthy_Aging_GWAS_2017_ABW-P01/Analysis/HAS_Het_Analysis_OLGA/Heterozygosity_tests"
  plink.MAF.path: "plink_output/MAF_X_gp_equal.frq"
  plink.hardy.path: "plink_output/HWE_X_gp_equal_cc.hwe"
  
  subgroup.pref: "GP_female_X_"  # options: "female_" "male_"
  stat.plots.dir: "EOH_GP_female_X_CHR" # if == "" plots will be save to the root of "plots" directory, otherwise to the the subdirectory
  snp.filter: "" # options: "HLA_" "syn_" ""nonsyn_" "coding_" "noncoding_" "intron_" "intergenic_" "X_CHR_"
  snp.filter.path: ""
 
  do.homozygosity.test: true # check for excess of homozygosity for a minor allele
  do.stat.test: true # Mann–Whitney U Test and Fligner test for each pair of groups
  do.odd.ratio.test: false
  
  save.plots:   true # save EoH distribution, QQ plots, scatter plots, barchart for MAF binc etc.
  save.plots.chr: false # save EoH for each chromosome: approximation using local polynomial regression & heatmap
  span: 0.1
